In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split


In [4]:
data=pd.read_csv('pgh_train.csv')

In [5]:
#print(data)

In [6]:
X=data.iloc[:,[0,1,2,3,5,6]].values
y=data.iloc[:,4].values # speed (Observed average speed over the segment at that time)
#X
#Y

In [7]:
from sklearn.preprocessing import Imputer

imputer=Imputer(missing_values='NaN',strategy='mean')

imputer.fit(X[:,0:])
X[:,0:]=imputer.transform(X[:,0:])

C:\Users\HP\AppData\Roaming\Python\Python37\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [8]:
#X

In [9]:
X_train, X_test, y_train, y_test= train_test_split(X,y,test_size=0.2,random_state=1)

#X_test
y_test

array([51.25184211, 25.51256757, 36.23674074,  6.8194898 , 17.44934211,
       16.44549451, 56.36793103, 18.26013699, 51.26800712, 19.01899083,
       15.01960526, 28.97796748, 10.6145    , 12.63068627, 12.78233333,
       21.21522727, 32.84077586, 26.52180451, 45.90470297, 31.18263538,
       24.06709677, 26.6223494 , 32.55375   , 35.65955446, 38.33263158,
       48.04120219, 11.72628571, 15.11536585, 17.57434783, 31.85198347,
       36.61709677, 26.18916667, 54.07201465, 31.92946667, 26.1172093 ,
       56.7790681 , 42.90032258, 23.96363636, 24.51837209, 43.076     ,
       26.33868966, 16.35026667, 23.10220588, 35.80576923, 33.27902256,
       28.82951923, 51.96236364, 12.9724    , 25.78267857, 20.22268041,
       12.79178571, 36.22961165, 27.6034375 , 21.4372449 , 52.06289474,
       23.98228261, 21.58428571, 17.43147059, 26.59884058, 54.17789216,
       15.52103175, 12.56696429, 27.27389474, 14.35694215, 11.48576087,
       37.69670732, 13.2664    , 25.16229008, 65.43183206, 18.55

In [10]:
reg=LinearRegression()
reg.fit(X_train,y_train)

y_predict=reg.predict(X_test)
y_predict

array([25.89894253, 24.61878236, 33.67080022, 29.15629068, 28.1301614 ,
       30.16616165, 31.1374674 , 25.92716829, 22.87981823, 30.61645953,
       27.12611465, 36.12131941, 27.18079283, 30.62785314, 36.31251901,
       30.0510154 , 30.56145281, 28.62526622, 19.35722677, 31.19856259,
       26.90091661, 29.07637343, 29.07968436, 34.11437912, 30.50587907,
       31.4618342 , 26.8265317 , 25.79872144, 27.47044473, 29.89258942,
       26.85194235, 29.32404909, 30.00910439, 24.17929366, 34.42227249,
       28.89290063, 30.71054423, 28.01807592, 29.39802881, 35.49739279,
       30.4560863 , 21.58132956, 29.51716243, 26.99512228, 37.50433309,
       25.12718877, 32.40009312, 25.75210447, 32.63475793, 34.34523199,
       35.65953242, 27.54235587, 27.64598257, 35.07525907, 33.7831068 ,
       26.24793003, 27.10391375, 29.78268881, 32.74128355, 30.41140681,
       29.19969657, 30.99365709, 23.89972607, 31.70551332, 32.17283342,
       32.32952003, 26.65719538, 29.55513139, 59.18980696, 25.44

In [11]:
#plt.scatter(X_train,y_train,color="red")
#plt.plot(X_train,reg.predict(X_train))
#plt.show()

In [13]:
np.mean((y_predict-y_test)**2)

171.82987494047885

In [115]:
x_from=float(input('Enter the From x value'))
y_from=float(input('Enter the From y value'))
x_to=float(input('Enter the to x value'))
y_to=float(input('Enter the to y value'))
time=float(input('Enter the time'))
is_weekday=float(input('Enter the whether it is weekday or not (1 or 0)'))
x_test1=[]
x_test1.append(x_from)
x_test1.append(y_from)
x_test1.append(x_to)
x_test1.append(y_to)
x_test1.append(time)
x_test1.append(is_weekday)

#x=np.array(x_test1)
#x.reshape(1,-1)
reg=LinearRegression()
reg.fit(X_train,y_train)

y_predict1=reg.predict([x_test1])
y_predict1

Enter the From x value-79.99836282672929	
Enter the From y value40.4370636187516	
Enter the to x value-79.9951103950099	
Enter the to y value40.4359318661507
Enter the time14
Enter the whether it is weekday or not (1 or 0)1


array([30.1261016])

In [1]:
#prediction using pred.csv dataset

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

data=pd.read_csv('pgh_pred.csv')

X=data.iloc[1:,:-1].values
y=data.iloc[1:,-1].values # speed (Observed average speed over the segment at that time)
#X
#y

In [2]:
from sklearn.preprocessing import Imputer

imputer=Imputer(missing_values='NaN',strategy='mean')

imputer.fit(X[:,0:])
X[:,0:]=imputer.transform(X[:,0:])

C:\Users\HP\AppData\Roaming\Python\Python37\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [3]:
X_train, X_test, y_train, y_test= train_test_split(X,y,test_size=0.2,random_state=1)

#X_test
#y_test
#X_train[1][0]
#len(X_train)


In [4]:
reg=LinearRegression()
reg.fit(X_train,y_train)

y_predict=reg.predict(X_test)
y_predict

array([28.31424022, 29.8138525 , 29.06404636, ..., 24.24327381,
       24.24327381, 24.56953043])

In [5]:
np.mean((y_predict-y_test)**2)

41.60566105035708

In [10]:
time=float(input('Enter the time'))
is_weekday=float(input('Enter whether it is weekday or not (1 or 0)'))
x_from=float(input('Enter the from x value'))
y_from=float(input('Enter the from y value'))
x_to=float(input('Enter the to x value'))
y_to=float(input('Enter the to y value'))
x_test1=[]
x_test1.append(time)
x_test1.append(is_weekday)
x_test1.append(x_from)
x_test1.append(y_from)
x_test1.append(x_to)
x_test1.append(y_to)

#x=np.array(x_test1)
#x.reshape(1,-1)
reg=LinearRegression()
reg.fit(X_train,y_train)

y_predict1=reg.predict([x_test1])
#y_predict1
print("The Traffic speed is %f"%(y_predict1))

Enter the time8
Enter whether it is weekday or not (1 or 0)1
Enter the from x value-79.86663
Enter the from y value40.452687
Enter the to x value-79.866439
Enter the to y value40.45279
The Traffic speed is 26.992657


In [47]:
#time_train=data.iloc[1:,0].values
"""
print(len(y_train))
time_train=[]
new_y_train=[]
for i in range(len(X_train)):
    time_train.append(X_train[i][0])
    new_y_train.append(y_train[i])
#print(new_y_train)
plt.scatter(list(time_train),list(new_y_train),color='red')
plt.plot(list(time_train),reg.predict([time_train]))
plt.show()
"""


"\nprint(len(y_train))\ntime_train=[]\nnew_y_train=[]\nfor i in range(len(X_train)):\n    time_train.append(X_train[i][0])\n    new_y_train.append(y_train[i])\n#print(new_y_train)\nplt.scatter(list(time_train),list(new_y_train),color='red')\nplt.plot(list(time_train),reg.predict([time_train]))\nplt.show()\n"