In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
from sklearn.svm import LinearSVR
from sklearn.model_selection import train_test_split
from sklearn import metrics


In [19]:
data=pd.read_csv('pgh_train.csv')

In [20]:
X=data.iloc[:,[0,1,2,3,5,6]].values
y=data.iloc[:,4].values # speed (Observed average speed over the segment at that time)
#X
#Y

In [21]:
from sklearn.preprocessing import Imputer

imputer=Imputer(missing_values='NaN',strategy='mean')

imputer.fit(X[:,0:])
X[:,0:]=imputer.transform(X[:,0:])

C:\Users\HP\AppData\Roaming\Python\Python37\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [22]:
X_train, X_test, y_train, y_test= train_test_split(X,y,test_size=0.2,random_state=1)

y_test

array([51.25184211, 25.51256757, 36.23674074,  6.8194898 , 17.44934211,
       16.44549451, 56.36793103, 18.26013699, 51.26800712, 19.01899083,
       15.01960526, 28.97796748, 10.6145    , 12.63068627, 12.78233333,
       21.21522727, 32.84077586, 26.52180451, 45.90470297, 31.18263538,
       24.06709677, 26.6223494 , 32.55375   , 35.65955446, 38.33263158,
       48.04120219, 11.72628571, 15.11536585, 17.57434783, 31.85198347,
       36.61709677, 26.18916667, 54.07201465, 31.92946667, 26.1172093 ,
       56.7790681 , 42.90032258, 23.96363636, 24.51837209, 43.076     ,
       26.33868966, 16.35026667, 23.10220588, 35.80576923, 33.27902256,
       28.82951923, 51.96236364, 12.9724    , 25.78267857, 20.22268041,
       12.79178571, 36.22961165, 27.6034375 , 21.4372449 , 52.06289474,
       23.98228261, 21.58428571, 17.43147059, 26.59884058, 54.17789216,
       15.52103175, 12.56696429, 27.27389474, 14.35694215, 11.48576087,
       37.69670732, 13.2664    , 25.16229008, 65.43183206, 18.55

In [23]:
reg=LinearSVR(C=1.0,epsilon=0.2,verbose=1)
reg.fit(X_train,y_train)

y_predict=reg.predict(X_test)
y_predict

[LibLinear]

C:\Users\HP\AppData\Roaming\Python\Python37\site-packages\sklearn\svm\base.py:931: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


array([16.04514549, 14.50321169, 15.29773877, 14.06176377, 12.48140691,
       15.28054958, 16.07410067, 13.24057726, 12.47099843, 16.05256375,
       13.27260089, 14.0669623 , 13.28649381, 16.08424466, 13.28116635,
       15.3108856 , 14.06419653, 14.03373179, 12.48586311, 14.07969658,
       15.2707166 , 13.25728421, 14.08112016, 13.28953465, 15.31763929,
       15.30568604, 12.50465111, 12.49363118, 14.48439645, 12.52593189,
       14.06112049, 14.06227552, 15.2947071 , 12.50015857, 14.54137725,
       16.06899983, 15.30171445, 12.50851083, 14.53400326, 15.31179497,
       16.06103636, 12.5359738 , 14.06443843, 13.28105348, 16.08922263,
       13.22135928, 14.0526731 , 15.30407504, 15.33296881, 14.07288162,
       12.504284  , 14.06288641, 12.51333721, 15.3182596 , 16.07493342,
       14.49383425, 14.498251  , 14.54947887, 15.28937213, 14.52144477,
       14.06477868, 15.30456958, 12.53861939, 16.08763161, 15.30662548,
       16.07233462, 14.48595523, 16.05662854, 16.07068838, 13.24

In [42]:
scores=reg.score(X,y)
print(scores)
#scores=scores*100
#print("Accuracy Score is: %.2f%%" % scores)
np.mean((y_predict-y_test)**2)

-2.350011042534743


154.49557811619115

In [8]:
x_from=float(input('Enter the From x value'))
y_from=float(input('Enter the From y value'))
x_to=float(input('Enter the to x value'))
y_to=float(input('Enter the to y value'))
time=float(input('Enter the time'))
is_weekday=float(input('Enter the whether it is weekday or not (1 or 0)'))
x_test1=[]
x_test1.append(x_from)
x_test1.append(y_from)
x_test1.append(x_to)
x_test1.append(y_to)
x_test1.append(time)
x_test1.append(is_weekday)

#x=np.array(x_test1)
#x.reshape(1,-1)
reg=LinearSVR(C=1.0,epsilon=0.2,verbose=1)
reg.fit(X_train,y_train)

y_predict1=reg.predict([x_test1])
y_predict1

Enter the From x value-80.03905685
Enter the From y value40.4358185
Enter the to x value-80.04081546
Enter the to y value40.40332719
Enter the time8
Enter the whether it is weekday or not (1 or 0)1
[LibSVM]

array([26.34803018])

In [1]:
#prediction using pred.csv dataset

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
from sklearn.svm import LinearSVR
from sklearn.model_selection import train_test_split

data=pd.read_csv('pgh_pred.csv')

X=data.iloc[1:,:-1].values
y=data.iloc[1:,-1].values # speed (Observed average speed over the segment at that time)
#X
#y

In [2]:
from sklearn.preprocessing import Imputer

imputer=Imputer(missing_values='NaN',strategy='mean')

imputer.fit(X[:,0:])
X[:,0:]=imputer.transform(X[:,0:])

C:\Users\HP\AppData\Roaming\Python\Python37\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [3]:
X_train, X_test, y_train, y_test= train_test_split(X,y,test_size=0.2,random_state=1)
y_test

array([18.88613877, 28.67356775, 33.94060031, ..., 19.75548676,
       17.91711416, 26.46032615])

In [4]:
reg=LinearSVR(C=1.0,epsilon=0.2,verbose=1)
reg.fit(X_train,y_train)

y_predict=reg.predict(X_test)
y_predict

[LibLinear]

C:\Users\HP\AppData\Roaming\Python\Python37\site-packages\sklearn\svm\base.py:931: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


array([23.22125723, 25.44745445, 24.33435584, ..., 19.20210632,
       19.20210632, 21.38101964])

In [5]:
np.mean((y_predict-y_test)**2)

63.973943730273525

In [6]:
time=float(input('Enter the time'))
is_weekday=float(input('Enter whether it is weekday or not (1 or 0)'))
x_from=float(input('Enter the from x value'))
y_from=float(input('Enter the from y value'))
x_to=float(input('Enter the to x value'))
y_to=float(input('Enter the to y value'))
x_test1=[]
x_test1.append(time)
x_test1.append(is_weekday)
x_test1.append(x_from)
x_test1.append(y_from)
x_test1.append(x_to)
x_test1.append(y_to)

#x=np.array(x_test1)
#x.reshape(1,-1)
reg=LinearSVR(C=1.0,epsilon=0.2,verbose=1)
reg.fit(X_train,y_train)

y_predict1=reg.predict([x_test1])
#y_predict1
print("The Traffic speed is %f"%(y_predict1))

Enter the time8
Enter whether it is weekday or not (1 or 0)1
Enter the from x value-79.86663
Enter the from y value40.452687
Enter the to x value-79.866439
Enter the to y value40.45279
[LibLinear]The Traffic speed is 31.721851


C:\Users\HP\AppData\Roaming\Python\Python37\site-packages\sklearn\svm\base.py:931: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
